language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=development
services:
  - mongodb
before_script:
  - mkdir certs && cd certs && openssl genrsa -out 127.0.0.1.key 2048 && openssl req -new -x509 -key 127.0.0.1.key -out 127.0.0.1.cert -days 3650 -subj /CN=127.0.0.1
script: "grunt test"