language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=development
services:
  - mongodb
script:
  - npm test
install:
  - "npm install"
  - "npm install grunt -g"
  - "mkdir certs && openssl genrsa -out certs/127.0.0.1.key 2048 && openssl req -new -x509 -key certs/127.0.0.1.key -out certs/127.0.0.1.cert -days 3650 -subj /CN=127.0.0.1"